openapi: 3.0.0
info:
  title: Customer API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
paths:
  /customers:
    get:
      summary: Get all customers with pagination
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /gender-stats:
    get:
      summary: Gender statistics
      responses:
        '200':
          description: OK
  /digital-interest-stats:
    get:
      summary: Digital Interest statistics
      responses:
        '200':
          description: OK
  /location-type-stats:
    get:
      summary: Location Type statistics
      responses:
        '200':
          description: OK
  /device-brand-stats:
    get:
      summary: Device Brand statistics
      responses:
        '200':
          description: OK
  /age-distribution:
    get:
      summary: Age distribution statistics
      responses:
        '200':
          description: OK
